### ISSUE TITLE
Why doesn't a new instance of a resource have the injected service?

### ISSUE THREAD

**Issue by barelyknown** [pixelhandler/ember-jsonapi-resources#10]
I have a route like this:

```javascript
import Ember from 'ember';
import Resource from 'scoreboard-www/models/game';

export default Ember.Route.extend({
  model: function() {
    return Resource.create({isNew: true});
  }
});
```

I noticed that the instance that is created by `model()` does not have the injected `service` defined. But, instances created by `deserialize()` (via `this.container.lookup(factoryName).create({})`) **do** have the `service` defined. I looked through the code but couldn't see why this would be. Any idea?

**Comment by pixelhandler** [comment]
@barelyknown the blueprint for a resource now has `service: Ember.inject.service('<%= resource %>'),` Also see the tests/dummy/app code I added a bunch of resources, essentially it's a small blog all to test with when working on the repo has to be started with a proxy url i.e. `ember server --proxy http://api/pixelhandler.com`
