### ISSUE TITLE
[question] Make related-proxy computed property volatile?

### ISSUE THREAD

**Issue by aars** [pixelhandler/ember-jsonapi-resources#109]
The `hasOne` and `hasMany` helpers create a computed property that returns a proxy object. This proxy object is then cached and used for every subsequent `get` of that relation. This means that either `related-proxy.promiseFromCache` or `service.findRelated` is always used. Which means:
- Cache is only used when it has contains the related resources on `proxySetup` and then cached. Making it impossible to use the related-proxy to query the server for relations afterwards.
- The reverse: Cache is never used if it did not contain the related resources on `proxySetup`. Subsequent `get`s of that relation will _always_ query the server.

I can't easily imagine this is by design. I think it mostly ends up being `service.findRelated`, so in most use-cases everything works fine. But I ran into this when I wondered why resources that were included in previous server responses were being fetched again.

I think an easy "fix" would be to add `.volatile()` to the `Ember.computed` we return in the `hasOne` and `hasMany` helpers. I don't see any impact other than performance (which could very well be significant).

There might be some other mechanisme in place that is supposed to provide this functionality (look for relation resources in cache first), maybe through the `PromiseProxyMixin`? But I don't think so/can't find any.

Cheerio.

**Comment by aars** [comment]
Mmmm... I just realized that the user needs some sort of control of where the resources are fetched from, either cache or server. `promiseFromCache` will only work on what ie a `Post` resource has stored in `relationships.comments.data`, and only if the `Comment` resources in that `data` are also cached in the `Comment` service. Only in that case will the cache be used, and never again the server queried.

In all other cases `service.findRelated` is going to be used.

Is there any use left for `promiseFromCache` in it's current setup?

**Comment by aars** [comment]
Maybe something like a `refresh` method on the Proxy object that will always query the server?

**Comment by pixelhandler** [comment]
@aars `promiseFromCache` usage in the `RelatedProxyUtil` was added for a specific use case. For example, fetching a list of resources that all have the same relationship object. Perhaps a list of blog posts all by the same author. So with a default cache time on the Resource prototype of 7 seconds the relationship (post's author) will be found in the cache. For a list of 10 posts this avoids 9 requests for the same author.

Each Resource's prototype (model class) can have custom cache settings, in addition the service can use custom cache settings. I use some resources (e.g. lists of options for dropdowns) that are set to cache for 24 hours. 

This wiki page has an example where the model hook checks cache first then fetches from server, https://github.com/pixelhandler/ember-jsonapi-resources/wiki/Cache

**Comment by pixelhandler** [comment]
@aars regarding adding a `refresh` method, I've been defining custom methods on various resources as needed to change default behavior or add new behavior. For example I may add a `findRelatedThings` method on the model that will use the service/adapter `findRelated`  method, see http://ember-jsonapi-resources.com/docs/classes/ApplicationAdapter.html#method_findRelated

**Comment by pixelhandler** [comment]
@aars any more thoughts on this topic?

**Comment by aars** [comment]
It's been a long time.

After re-reading this issue and the code, I still don't see how this construction will fall back to server requests after cache is expired. If `proxySetup` is only run once, it will only decide on this once:
```
let promise = this.promiseFromCache(resource, relation, service);
promise = promise || service.findRelated({'relation': relation, 'type': type}, url);
```

I'll have to tripple-check if it is indeed only run once. If this is an actual issue, I will run into it again very soon. So I'll close this for now and research when it pops up again.
