### ISSUE TITLE
changedRelationships does not track first hasOne

### ISSUE THREAD

**Issue by aars** [pixelhandler/ember-jsonapi-resources#110]
Because of this check in `ref.previous` an hasOne relationship that was previously empty will not show up in `changedAttributes` since `ref.previous` is `null`.

https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js#L373

**Comment by aars** [comment]
I think that should be `return !!ref.changed || (ref.removals && ref.removals.length) || (ref.added && ref.added.length);`

**Comment by pixelhandler** [comment]
@aars so change `!!ref.previous` to `!!ref.changed`.  Is there anything in this test that appears to not test your use case? https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/tests/unit/models/resource-test.js#L305-L321

**Comment by aars** [comment]
@pixelhandler I'm sorry, that was some horrible issue-reporting by me.

Yes. That test does not check if `changedRelationships` will contain the `author` after that first `addRelationship`. Proof and fix in [this PR](https://github.com/pixelhandler/ember-jsonapi-resources/pull/111)

**Comment by pixelhandler** [comment]
@aars released 1.5.2 - https://github.com/pixelhandler/ember-jsonapi-resources/releases
