### ISSUE TITLE
[question] Similaries/differences with `DS.JSONAPIAdapter`?

### ISSUE THREAD

**Issue by rmharrison** [pixelhandler/ember-jsonapi-resources#114]
Was just wondering what the similiaries / differences were between this addon and  the ember-data core supported [DS.JSONAPIAdapter](http://emberjs.com/api/data/classes/DS.JSONAPIAdapter.html)?

In other words, when should I use this addon, and when would `DS.JSONAPIAdapter` be sufficient?

**Comment by pixelhandler** [comment]
@rmharrison if you want to support *only*  the JSON API spec in your app, this addon is designed for just that. 

See the intro in the Guide: https://guide.ember-jsonapi-resources.com

> **The primary goal of this library is to treat your API contract as first class in your application.** The application data and responses from your API both reflect the nomenclature of the API contract. That contract is the JSON API 1.0 specification.

The similarities are as you would expect, similar design pattern for adapters/serializer ; services via a store. The differences are that this library is tiny by comparison as it only supports JSON API. Another main difference is that this library doesn't abstract the way in which you interact with the API contract (server payloads); the nomenclature and format are simply represented in the same fashion in the app.
