### ISSUE TITLE
Create blueprints for Route files

### ISSUE THREAD

**Issue by pixelhandler** [pixelhandler/ember-jsonapi-resources#2]
Consider using the plural name for the resource or whether to follow the singular name like Ember uses in the default model hooks.

**Comment by pixelhandler** [comment]
closing this the store accepts a singular name for the resource and pluralizes it to lookup the service for the resource which is plural, e.g. /posts has a 'posts' service used by the store; but you can as for all posts like ember does `this.store.find('post')`

**Comment by mrlee-io** [comment]
What about pod support?  All the learning material suggests that is the way forward right now.

**Comment by pixelhandler** [comment]
@mrlee-io that's a good idea, pod support for the blueprints. I'll create an issue for that.

**Comment by pixelhandler** [comment]
see: https://github.com/pixelhandler/ember-jsonapi-resources/issues/16
