### ISSUE TITLE
Resource generator, routing structure + integration with JSONAPI::Resources

### ISSUE THREAD

**Issue by oliverbarnes** [pixelhandler/ember-jsonapi-resources#21]
(Question about usage really, wasn't sure whether to post this on StackOverflow. I didn't find any ember-jsonapi-resources questions or tags there, so asking here. Happy to update the README accordingly afterwards, if relevant for documentation)

I have a rails api using JR, with a `/proposals` endpoint for a Proposal resource/model. I'm building a form for a new proposal on my ember front-end, and after installing ember-jsonapi-resources I generated a resource with `ember g resource proposal`.

I noticed the route generated and appended to `router.js` is in the singular, which threw me off a bit - I was (naively, probably) expecting a route in the plural, matching the rails convention, and since the jsonapi convention is also to refer to resources in the plural. 

What's the recommended way to structure routes, that will work most seamlessly with ember-jsonapi-resources/JR? The dummy app's routing structure seems a little fuzzy on this:

```
  this.route('index', { path: '/' });
  this.resource('post', { path: '/:post_id' }, function () {
    this.route('detail', { path: '/' });
    this.route('comments');
  });
  this.route('admin', function () {
    this.route('index');
    this.route('create');
    this.route('edit', { path: ':edit_id' });
  });
```

For the `proposal` resource creation example, should a route for `new` (or `create`?) be nested under the singular proposal route like this?

```
this.route('proposal', function() {
  this.route('new');
  // # and then,
  //this.route('edit'); ?
  // # and possibly
  //this.route('index'); ?
});
```

...Or does it simply not matter, and any route structure will work the same with both ember-jsonapi-resources and JR?

**Comment by pixelhandler** [comment]
@oliverbarnes I've been meaning to write up an article on routing in Ember as defining your user interface vs mimicking your backed resources. The Ember routes in an app should describe the user interface and may or may not reflect how resources are structured on your API server.

The route that is generated is the default behavior of Ember CLI; all the other generated files are specific to ember-JSONAPI-resources

**Comment by oliverbarnes** [comment]
This makes total sense, and coming from backend dev I do tend to forget
it. That said, the specific interface I'm building right now is a simple
form to create a new resource that maps exactly do a backend resource.

How would you design in the routing in this case, and what works more
seamlessly with both ember-jsonapi-resources and JR?

**Comment by pixelhandler** [comment]
@oliverbarnes the example app in this repo uses `index` as `/` for the home page a list of resources. this is the default behavior. In other apps I've used `this.route('list', { path: '/' });` as 'list' describes the interface. Also in the example app I've used `admin` as parent route for `create` and `edit` have you tried cloning this repo and running `ember server --proxy http://api.pixelhandler.com` ? then you can see exactly what you've described an admin form to edit one resource.
