### ISSUE TITLE
"Dasherize" resource attributes

### ISSUE THREAD

**Issue by vinnicc** [pixelhandler/ember-jsonapi-resources#28]
Just recommending that keys given to `Resource#attr` be dasherized by default. This makes serialization same with the `jsonapi-resources` gem, and since the official spec hints at this convention anyway. Thanks!

**Comment by pixelhandler** [comment]
@vinnicc yeah the http://jsonapi.org/recommendations/#naming page recommends separating words an an name with the minus sign (dash). Perhaps an assert can be used to suggest via console warn that the recommended naming convention is to use dasherized attributes.
