### ISSUE TITLE
Use service cache for relations in the resource (model)

### ISSUE THREAD

**Issue by pixelhandler** [pixelhandler/ember-jsonapi-resources#3]
The proxied attribute for a resources's relations may need to check the service cache rather than may new request for relationships.

**Comment by barelyknown** [comment]
Have you thought much about this design? I can help implement it (I'll be working on something related soon).

**Comment by pixelhandler** [comment]
@barelyknown haven't thought to much about it yet, other than I'd like to to be super flexible. I'd rather developer have control over the caching rules for their apps. This rfc https://github.com/jcollins1991/rfcs/blob/master/active/0000-data-loading-methods.md made me think that every app will have it's own needs for getting from cache in memory or from fetching from the server.

Awhile back I build a frame work that would get from storage if not expired then fetch from server. So my initial though is that in the helpers for `hasOne` and `hasMany` we'll need hook to get from cache that developer can define how they want to do that. the default implementation can have a `expiresIn` value on the resource prototype and use the cache if that resource has a meta timestamp that is less than the expires time, e.g. 7 minutes or something like that.

Also by giving that hook not the resource (model) some data can be even set on localStorage and read there too.

**Comment by barelyknown** [comment]
I agree that a one-size-fits-all solution will be elusive. A solid set of hooks, maybe some out-of-the-box support for common strategies, and a cookbook of examples would be great.

Perhaps that means that we should start with the cookbook. As we implement examples of common strategies the abstraction will emerge.
