### ISSUE TITLE
Remove unneeded `container.register` from initializer.

### ISSUE THREAD

**Issue by rwjblue** [pixelhandler/ember-jsonapi-resources#32]
Because the `service:store` is already available (since it is exported at `app/services/store.js` it will be auto-resolved without issue), you do not need to manually register it.

https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/initializers/store.js#L16

**Comment by pixelhandler** [comment]
@rwjblue So these (in a blueprint) can go away too then https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/blueprints/initializer/files/__root__/initializers/__name__.js#L8-L10 correct?

**Comment by pixelhandler** [comment]
@rwjblue I tried removing the manual registration for `service:store` but that breaks the dummy app as resources need to inject related services into the store service like `application.inject('service:store', 'authors', 'service:authors');` But without manually registering the store service it is not available via an initializer to make an injection.
