### ISSUE TITLE
Why the separate call to hasRelated?

### ISSUE THREAD

**Issue by barelyknown** [pixelhandler/ember-jsonapi-resources#6]
I just read through [resource.js] (which was a real pleasure - such nice code). It wasn't clear to me why there needs to be a separate call to `hasRelated` to register the relationships (instead of having `hasOne` and `hasMany` do that). I suspect I'm missing a consideration in your design. Would you mind explaining?

[resource.js]: https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js

**Comment by pixelhandler** [comment]
@barelyknown at first I didn't use the hasRelated method only a `relationships` object. later I found a need to setup the object so I added this method to setup the relationships object. but I'm open to changing that, it came it mostly to make things work. I still like the idea of declaring the relationships object in the resource prototype. A JSON API resource has props for id, type, links, relationships, attributes. The hasOne and hasMany setup the computed properties using a promise proxy to fetch the related objects. Perhaps `hasRelated()` should just become `relationships()` that would be more inline with the definition of a resource that is represented by the JSON API.  I considered avoiding it altogether and using the hasOne and hasMany to setup the relationships' (links) objects with `{ links: {}, data: null }`, see https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js#L160-L170

**Comment by barelyknown** [comment]
It felt to me like it should just be `relationships()` and that `hasOne()` and `hasMany()` should setup the relationships object using `newRelation()`. Otherwise, users might be confused about why they have to declare the relationship twice.

**Comment by pixelhandler** [comment]
@barelyknown the computed properties don't access the model (this) until a get is called so I was concerned that I needed to setup the relationships straight away so if the resource is serialized the `relationships` part of the resource would be accurate. At first it seem odd to declare the releationships then also the related proxies to those related resources but essentially they are two things once is for the structure of the resource's relationships objects and the other (hasOne/hasMany) is for actual proxied (related) resources.

**Comment by barelyknown** [comment]
It seems like there should be something above `hasOne()`/`hasMany()` and `hasRelationships()` that sets up the proxy and adds to the `relationships`. Maybe that's too much "magic" and doesn't matter much, but it seems like now is the time to talk about the API. I also wanted to make sure that I understood why you made the choice (and I do).

**Comment by pixelhandler** [comment]
@barelyknown I'll put the change in the next release to use only `hasOne()` `hasMany()` and setup the `reltationships` object during `init`.
