### ISSUE TITLE
Update to authorization mixin to support ember-simple-auth 1.0

### ISSUE THREAD

**Issue by oliverbarnes** [pixelhandler/ember-jsonapi-resources#63]
I'm updating ember-simple-auth to 1.0 on Participate, In order to start using its session service. While checking out the source, I found this [data adapter mixin for Ember Data](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/data-adapter-mixin.js).

I'm wondering how to tweak it so it'll work with EJR?

**Comment by pixelhandler** [comment]
@oliverbarnes I'll close this out for now I have not used ESA with this library so don't know
