### ISSUE TITLE
model generator/blueprint broken?

### ISSUE THREAD

**Issue by aars** [pixelhandler/ember-jsonapi-resources#83]
using ember-cli 2.5.1 `ember generate jsonapi-resource model-name [--classic]` creates broken model files, it seems to have something to do with the length of `model-name`.

steps to reproduce:
```
$ ember new ember-jsonapi-resources-blueprint-test
$ cd ember-jsonapi-resources-blueprint-test
$ ember install ember-jsonapi-resources
$ ember generate jsonapi-resource resource-test --classic
$ ember generate jsonapi-resource testing
$ ember generate jsonapi-resource testing2
```

`app/models/resource-test.js` now looks like this:
```js
export { default } from 'ember-jsonapi-resources-blueprint-test/models/resource-test';
e';
import { attr, hasOne, hasMany } from 'ember-jsonapi-resources/models/resource';

let ResourceTest = Resource.extend({
  type: 'resource-tests',
  service: Ember.inject.service('resource-tests'),


});

ResourceTest.reopenClass({

  getDefaults() {
    return {
      isNew: true,
      attributes: {}
    };
  }
});

export default ResourceTest;
```

The import/exports are broken. Not sure if the `export { default }` line should even be there.
`app/model/testing.js`
```js
export { default } from 'ember-jsonapi-resources-blueprint-test/models/testing';
esource';
import { attr, hasOne, hasMany } from 'ember-jsonapi-resources/models/resource';

...
```

`app/model/testing2.js`:
```js
xport { default } from 'ember-jsonapi-resources-blueprint-test/models/testing2';
source';
import { attr, hasOne, hasMany } from 'ember-jsonapi-resources/models/resource';

...
```

As you can see, the second line (which should `import Resource`) is 1 char shorter in `testing2`, which is why I think the `model-name` length is involved here.

**Comment by aars** [comment]
This is what I make of it to get the models working:
```
  import Ember from 'ember';
  import Resource from 'ember-jsonapi-resources/models/resource';
  import { attr, hasOne, hasMany } from 'ember-jsonapi-resources/models/resource';
```

**Comment by pixelhandler** [comment]
@aars yeah that looks proper. I'll take a look at the generator. As a work around you could copy paste from the blueprint and fix the paths. Looks like the model blueprint had trouble with the dasherized name `model-name` format.

**Comment by aars** [comment]
Fixed here? https://github.com/pixelhandler/ember-jsonapi-resources/pull/98

**Comment by pixelhandler** [comment]
@aars thanks for working on a solution.
